 export const fruitsdata=[
    {
        name:"sunflower",
        type:"flower",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb3SkrKNVw_Qy5g8qTYBIjUbnMl5iNvOyadukp2JRL9A&s"
    },
    {
        name:"apple",
        type:"fruit",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgD34d_X4yEWZ6wZ6Vr-AaR78eRVYzXfDkDo0AsRMQbA&s"
    },
    {
        name:"potato",
        type:"vegetable",
        image:"https://static.toiimg.com/photo/92522114.cms"
    },
    {
        name:"rose",
        type:"flower",
        image:"https://hips.hearstapps.com/hmg-prod/images/bunch-of-roses-as-a-bed-royalty-free-image-964650398-1554826447.jpg"
    },
    {
        name:"mango",
        type:"fruit",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/640px-Mangos_-_single_and_halved.jpg"
    },
    {
        name:"tomato",
        type:"vegetable",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJdcyZg5tcu1d7UYbfCKJTkzkjC3-IBJoT67oxQV9xQA&s"
    },
    {
        name:"marigold",
        type:"flower",
        image:"https://naturerabbit.in/wp-content/uploads/2018/08/Nature-Rabbit-African-marigold-Orange-Plant.jpg"
    },
    {
        name:"pineapple",
        type:"fruit",
        image:"https://media6.ppl-media.com/mediafiles/blogs/pineapple_6439817058.jpg"
    },
    {
        name:"cauliflower",
        type:"vegetable",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQfwvLUoqgBpBK5sBpEfICVWoFbT4hoiTJtzEfhoNFEg&s"
    },
    {
        name:"lily",
        type:"flower",
        image:"https://media.istockphoto.com/id/105813631/photo/white-lilies-in-a-garden.webp?b=1&s=612x612&w=0&k=20&c=dcLd978CXVf0rA2KQae4cu5AD9P8e7lPygrfp9X_pY0="
    },
    {
        name:"watermelon",
        type:"fruit",
        image:"https://blog-images-1.pharmeasy.in/2020/08/28152823/shutterstock_583745164-1.jpg"
    },
    {
        name:"capsicum",
        type:"vegetable",
        image:"https://images.indianexpress.com/2023/09/Capsicum.jpg"
    }
]
   

    
